#SECRET.YAML 
apiVersion: v1
kind: Secret
metadata: 
  name: argo-private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/h3itham/hive-box.git
  username: h3itham 
  password:  # ADD YOUR GITHUB TOKEN HERE. 
