#SECRET.YAML 
apiVersion: v1
kind: Secret
metadata: 
  name: argo-private-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/USERNAME/REPONAME.git
  username: GITHUB-USERNAME
  password: ADD YOUR GITHUB TOKEN HERE. 
