--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hivebox-tls 
  namespace: hive-box
spec:
  secretName: hivebox-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hivebox.haithamelabd.com