# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: hive-
namespace: hive-box

resources:
- 01-backend-dep-svc.yml
- 02-backend-config.yml 
- 03-frontend-dep-svc.yml
- 04-nginxconf.yml
- 05-redis.yml
- 06-minIO.yml
- 07-nginx-ingress.yml

labels:
- pairs:
    app.kubernetes.io/part-of: hive-box
    environment: base