# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hive-box

resources:
- 01-backend-dep-svc.yml
- 02-backend-config.yml 
- 03-frontend-dep-svc.yml
- 04-frontend-ingress.yml
- 05-nginxconf.yml
- 06-certificate.yml
- 07-redis.yml
- 08-minIO.yml

labels:
- pairs:
    app.kubernetes.io/part-of: hive-box
    environment: base