# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: hive-box-dev

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend-hive
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: hive-backend
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            env:
            - name: ENVIRONMENT
              value: "development"
  target:
    kind: Deployment
    name: backend-hive

- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-hivebox
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: frontend-hivebox
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
  target:
    kind: Deployment
    name: frontend-hivebox